### PR TITLE
[Feature: RA-63]:Initialised DB connection

### PR DESCRIPTION
**Pull request by ritvik130**

### CODE REVIEW

**Comment by ritvik130** [comment]
I do not like how my password is visible in env files, if you have a better way lmk

**Comment by ZainMalik00** [comment]
@ritvik130 here are potential solutions 
https://stackoverflow.com/questions/34668804/mongoose-hide-password-in-uri

**Comment by ZainMalik00** [comment]
@ritvik130 The .env file from the first commit is still in the PR. Could you remove it? I'll approve the PR there after

**Comment by ritvik130** [comment]
Done @ZainMalik00

**Review by ZainMalik00 — APPROVED** [review]

**Pull request merged**
